// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/opaque.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ClientLoginFinishResult dco_decode_client_login_finish_result(dynamic raw);

  @protected
  ClientLoginStartResult dco_decode_client_login_start_result(dynamic raw);

  @protected
  ClientRegistrationFinishResult dco_decode_client_registration_finish_result(
    dynamic raw,
  );

  @protected
  ClientRegistrationStartResult dco_decode_client_registration_start_result(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  ServerLoginStartResult dco_decode_server_login_start_result(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ClientLoginFinishResult sse_decode_client_login_finish_result(
    SseDeserializer deserializer,
  );

  @protected
  ClientLoginStartResult sse_decode_client_login_start_result(
    SseDeserializer deserializer,
  );

  @protected
  ClientRegistrationFinishResult sse_decode_client_registration_finish_result(
    SseDeserializer deserializer,
  );

  @protected
  ClientRegistrationStartResult sse_decode_client_registration_start_result(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ServerLoginStartResult sse_decode_server_login_start_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_client_login_finish_result(
    ClientLoginFinishResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_client_login_start_result(
    ClientLoginStartResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_client_registration_finish_result(
    ClientRegistrationFinishResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_client_registration_start_result(
    ClientRegistrationStartResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_login_start_result(
    ServerLoginStartResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
