// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/opaque.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 577101344;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_opaque',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ClientLoginFinishResult> crateApiOpaqueClientLoginFinish({
    required PlatformInt64 stateId,
    required List<int> password,
    required List<int> credentialResponse,
  });

  Future<ClientLoginStartResult> crateApiOpaqueClientLoginStart({
    required List<int> password,
  });

  Future<ClientRegistrationFinishResult>
  crateApiOpaqueClientRegistrationFinish({
    required PlatformInt64 stateId,
    required List<int> password,
    required List<int> registrationResponse,
  });

  Future<ClientRegistrationStartResult> crateApiOpaqueClientRegistrationStart({
    required List<int> password,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<Uint8List> crateApiOpaqueServerLoginFinish({
    required PlatformInt64 stateId,
    required List<int> credentialFinalization,
  });

  Future<ServerLoginStartResult> crateApiOpaqueServerLoginStart({
    required List<int> serverSetup,
    required List<int> passwordFile,
    required List<int> credentialRequest,
    required List<int> credentialIdentifier,
  });

  Future<Uint8List> crateApiOpaqueServerRegistrationFinish({
    required List<int> registrationUpload,
  });

  Future<Uint8List> crateApiOpaqueServerRegistrationStart({
    required List<int> serverSetup,
    required List<int> registrationRequest,
    required List<int> credentialIdentifier,
  });

  Future<Uint8List> crateApiOpaqueServerSetupNew();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ClientLoginFinishResult> crateApiOpaqueClientLoginFinish({
    required PlatformInt64 stateId,
    required List<int> password,
    required List<int> credentialResponse,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(stateId, serializer);
          sse_encode_list_prim_u_8_loose(password, serializer);
          sse_encode_list_prim_u_8_loose(credentialResponse, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_client_login_finish_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueClientLoginFinishConstMeta,
        argValues: [stateId, password, credentialResponse],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueClientLoginFinishConstMeta =>
      const TaskConstMeta(
        debugName: "client_login_finish",
        argNames: ["stateId", "password", "credentialResponse"],
      );

  @override
  Future<ClientLoginStartResult> crateApiOpaqueClientLoginStart({
    required List<int> password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_client_login_start_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueClientLoginStartConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueClientLoginStartConstMeta =>
      const TaskConstMeta(
        debugName: "client_login_start",
        argNames: ["password"],
      );

  @override
  Future<ClientRegistrationFinishResult>
  crateApiOpaqueClientRegistrationFinish({
    required PlatformInt64 stateId,
    required List<int> password,
    required List<int> registrationResponse,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(stateId, serializer);
          sse_encode_list_prim_u_8_loose(password, serializer);
          sse_encode_list_prim_u_8_loose(registrationResponse, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_client_registration_finish_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueClientRegistrationFinishConstMeta,
        argValues: [stateId, password, registrationResponse],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueClientRegistrationFinishConstMeta =>
      const TaskConstMeta(
        debugName: "client_registration_finish",
        argNames: ["stateId", "password", "registrationResponse"],
      );

  @override
  Future<ClientRegistrationStartResult> crateApiOpaqueClientRegistrationStart({
    required List<int> password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_client_registration_start_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueClientRegistrationStartConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueClientRegistrationStartConstMeta =>
      const TaskConstMeta(
        debugName: "client_registration_start",
        argNames: ["password"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Uint8List> crateApiOpaqueServerLoginFinish({
    required PlatformInt64 stateId,
    required List<int> credentialFinalization,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(stateId, serializer);
          sse_encode_list_prim_u_8_loose(credentialFinalization, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueServerLoginFinishConstMeta,
        argValues: [stateId, credentialFinalization],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueServerLoginFinishConstMeta =>
      const TaskConstMeta(
        debugName: "server_login_finish",
        argNames: ["stateId", "credentialFinalization"],
      );

  @override
  Future<ServerLoginStartResult> crateApiOpaqueServerLoginStart({
    required List<int> serverSetup,
    required List<int> passwordFile,
    required List<int> credentialRequest,
    required List<int> credentialIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(serverSetup, serializer);
          sse_encode_list_prim_u_8_loose(passwordFile, serializer);
          sse_encode_list_prim_u_8_loose(credentialRequest, serializer);
          sse_encode_list_prim_u_8_loose(credentialIdentifier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_server_login_start_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueServerLoginStartConstMeta,
        argValues: [
          serverSetup,
          passwordFile,
          credentialRequest,
          credentialIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueServerLoginStartConstMeta =>
      const TaskConstMeta(
        debugName: "server_login_start",
        argNames: [
          "serverSetup",
          "passwordFile",
          "credentialRequest",
          "credentialIdentifier",
        ],
      );

  @override
  Future<Uint8List> crateApiOpaqueServerRegistrationFinish({
    required List<int> registrationUpload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(registrationUpload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueServerRegistrationFinishConstMeta,
        argValues: [registrationUpload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueServerRegistrationFinishConstMeta =>
      const TaskConstMeta(
        debugName: "server_registration_finish",
        argNames: ["registrationUpload"],
      );

  @override
  Future<Uint8List> crateApiOpaqueServerRegistrationStart({
    required List<int> serverSetup,
    required List<int> registrationRequest,
    required List<int> credentialIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(serverSetup, serializer);
          sse_encode_list_prim_u_8_loose(registrationRequest, serializer);
          sse_encode_list_prim_u_8_loose(credentialIdentifier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueServerRegistrationStartConstMeta,
        argValues: [serverSetup, registrationRequest, credentialIdentifier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueServerRegistrationStartConstMeta =>
      const TaskConstMeta(
        debugName: "server_registration_start",
        argNames: [
          "serverSetup",
          "registrationRequest",
          "credentialIdentifier",
        ],
      );

  @override
  Future<Uint8List> crateApiOpaqueServerSetupNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpaqueServerSetupNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpaqueServerSetupNewConstMeta =>
      const TaskConstMeta(debugName: "server_setup_new", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ClientLoginFinishResult dco_decode_client_login_finish_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ClientLoginFinishResult(
      credentialFinalization: dco_decode_list_prim_u_8_strict(arr[0]),
      sessionKey: dco_decode_list_prim_u_8_strict(arr[1]),
      exportKey: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  ClientLoginStartResult dco_decode_client_login_start_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ClientLoginStartResult(
      stateId: dco_decode_i_64(arr[0]),
      credentialRequest: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  ClientRegistrationFinishResult dco_decode_client_registration_finish_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ClientRegistrationFinishResult(
      registrationUpload: dco_decode_list_prim_u_8_strict(arr[0]),
      exportKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  ClientRegistrationStartResult dco_decode_client_registration_start_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ClientRegistrationStartResult(
      stateId: dco_decode_i_64(arr[0]),
      registrationRequest: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ServerLoginStartResult dco_decode_server_login_start_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ServerLoginStartResult(
      stateId: dco_decode_i_64(arr[0]),
      credentialResponse: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ClientLoginFinishResult sse_decode_client_login_finish_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_credentialFinalization = sse_decode_list_prim_u_8_strict(
      deserializer,
    );
    var var_sessionKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_exportKey = sse_decode_list_prim_u_8_strict(deserializer);
    return ClientLoginFinishResult(
      credentialFinalization: var_credentialFinalization,
      sessionKey: var_sessionKey,
      exportKey: var_exportKey,
    );
  }

  @protected
  ClientLoginStartResult sse_decode_client_login_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stateId = sse_decode_i_64(deserializer);
    var var_credentialRequest = sse_decode_list_prim_u_8_strict(deserializer);
    return ClientLoginStartResult(
      stateId: var_stateId,
      credentialRequest: var_credentialRequest,
    );
  }

  @protected
  ClientRegistrationFinishResult sse_decode_client_registration_finish_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_registrationUpload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_exportKey = sse_decode_list_prim_u_8_strict(deserializer);
    return ClientRegistrationFinishResult(
      registrationUpload: var_registrationUpload,
      exportKey: var_exportKey,
    );
  }

  @protected
  ClientRegistrationStartResult sse_decode_client_registration_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stateId = sse_decode_i_64(deserializer);
    var var_registrationRequest = sse_decode_list_prim_u_8_strict(deserializer);
    return ClientRegistrationStartResult(
      stateId: var_stateId,
      registrationRequest: var_registrationRequest,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ServerLoginStartResult sse_decode_server_login_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stateId = sse_decode_i_64(deserializer);
    var var_credentialResponse = sse_decode_list_prim_u_8_strict(deserializer);
    return ServerLoginStartResult(
      stateId: var_stateId,
      credentialResponse: var_credentialResponse,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_client_login_finish_result(
    ClientLoginFinishResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.credentialFinalization, serializer);
    sse_encode_list_prim_u_8_strict(self.sessionKey, serializer);
    sse_encode_list_prim_u_8_strict(self.exportKey, serializer);
  }

  @protected
  void sse_encode_client_login_start_result(
    ClientLoginStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.stateId, serializer);
    sse_encode_list_prim_u_8_strict(self.credentialRequest, serializer);
  }

  @protected
  void sse_encode_client_registration_finish_result(
    ClientRegistrationFinishResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.registrationUpload, serializer);
    sse_encode_list_prim_u_8_strict(self.exportKey, serializer);
  }

  @protected
  void sse_encode_client_registration_start_result(
    ClientRegistrationStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.stateId, serializer);
    sse_encode_list_prim_u_8_strict(self.registrationRequest, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_server_login_start_result(
    ServerLoginStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.stateId, serializer);
    sse_encode_list_prim_u_8_strict(self.credentialResponse, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
