// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `next_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DefaultCS`

/// Generate a new ServerSetup (server's static key pair + OPRF seed).
/// Store the returned bytes securely on the server — they must persist across
/// registrations and logins.
Future<Uint8List> serverSetupNew() =>
    RustLib.instance.api.crateApiOpaqueServerSetupNew();

/// Step 1 (client): Start registration.
/// Returns a state handle and the registration request to send to the server.
Future<ClientRegistrationStartResult> clientRegistrationStart({
  required List<int> password,
}) => RustLib.instance.api.crateApiOpaqueClientRegistrationStart(
  password: password,
);

/// Step 3 (client): Finish registration.
/// `state_id` must match the one returned from `client_registration_start`.
/// `registration_response` is the bytes received from the server (step 2).
/// Consumes the stored state — do not call twice for the same `state_id`.
Future<ClientRegistrationFinishResult> clientRegistrationFinish({
  required PlatformInt64 stateId,
  required List<int> password,
  required List<int> registrationResponse,
}) => RustLib.instance.api.crateApiOpaqueClientRegistrationFinish(
  stateId: stateId,
  password: password,
  registrationResponse: registrationResponse,
);

/// Step 2 (server): Process the client's registration request.
/// Returns the registration response bytes to send back to the client.
Future<Uint8List> serverRegistrationStart({
  required List<int> serverSetup,
  required List<int> registrationRequest,
  required List<int> credentialIdentifier,
}) => RustLib.instance.api.crateApiOpaqueServerRegistrationStart(
  serverSetup: serverSetup,
  registrationRequest: registrationRequest,
  credentialIdentifier: credentialIdentifier,
);

/// Step 4 (server): Finalise registration.
/// Returns the serialised password file — store this securely, keyed by the
/// credential identifier (username, user-id, etc.).
Future<Uint8List> serverRegistrationFinish({
  required List<int> registrationUpload,
}) => RustLib.instance.api.crateApiOpaqueServerRegistrationFinish(
  registrationUpload: registrationUpload,
);

/// Step 1 (client): Start login.
/// Returns a state handle and the credential request to send to the server.
Future<ClientLoginStartResult> clientLoginStart({
  required List<int> password,
}) => RustLib.instance.api.crateApiOpaqueClientLoginStart(password: password);

/// Step 3 (client): Finish login.
/// Returns the credential finalization to send to the server plus the session
/// key and export key on success.  Returns an error if the password is wrong
/// (the client detects this before the server).
Future<ClientLoginFinishResult> clientLoginFinish({
  required PlatformInt64 stateId,
  required List<int> password,
  required List<int> credentialResponse,
}) => RustLib.instance.api.crateApiOpaqueClientLoginFinish(
  stateId: stateId,
  password: password,
  credentialResponse: credentialResponse,
);

/// Step 2 (server): Process the client's credential request.
/// `password_file` is what was stored by `server_registration_finish`.
/// Returns a state handle and the credential response to send to the client.
Future<ServerLoginStartResult> serverLoginStart({
  required List<int> serverSetup,
  required List<int> passwordFile,
  required List<int> credentialRequest,
  required List<int> credentialIdentifier,
}) => RustLib.instance.api.crateApiOpaqueServerLoginStart(
  serverSetup: serverSetup,
  passwordFile: passwordFile,
  credentialRequest: credentialRequest,
  credentialIdentifier: credentialIdentifier,
);

/// Step 4 (server): Finalise login.
/// Returns the session key on success; the caller should compare this with the
/// client's session key out-of-band (or use it to verify an authenticated
/// message from the client).
Future<Uint8List> serverLoginFinish({
  required PlatformInt64 stateId,
  required List<int> credentialFinalization,
}) => RustLib.instance.api.crateApiOpaqueServerLoginFinish(
  stateId: stateId,
  credentialFinalization: credentialFinalization,
);

class ClientLoginFinishResult {
  /// Serialized CredentialFinalization — send this to the server.
  final Uint8List credentialFinalization;

  /// Session key agreed upon with the server.
  final Uint8List sessionKey;

  /// Export key derived from the password (can be used for local encryption).
  final Uint8List exportKey;

  const ClientLoginFinishResult({
    required this.credentialFinalization,
    required this.sessionKey,
    required this.exportKey,
  });

  @override
  int get hashCode =>
      credentialFinalization.hashCode ^
      sessionKey.hashCode ^
      exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientLoginFinishResult &&
          runtimeType == other.runtimeType &&
          credentialFinalization == other.credentialFinalization &&
          sessionKey == other.sessionKey &&
          exportKey == other.exportKey;
}

class ClientLoginStartResult {
  /// Opaque handle; pass this back to `client_login_finish`.
  final PlatformInt64 stateId;

  /// Serialized CredentialRequest — send this to the server.
  final Uint8List credentialRequest;

  const ClientLoginStartResult({
    required this.stateId,
    required this.credentialRequest,
  });

  @override
  int get hashCode => stateId.hashCode ^ credentialRequest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientLoginStartResult &&
          runtimeType == other.runtimeType &&
          stateId == other.stateId &&
          credentialRequest == other.credentialRequest;
}

class ClientRegistrationFinishResult {
  /// Serialized RegistrationUpload — send this to the server.
  final Uint8List registrationUpload;

  /// Export key derived from the password (can be used for local encryption).
  final Uint8List exportKey;

  const ClientRegistrationFinishResult({
    required this.registrationUpload,
    required this.exportKey,
  });

  @override
  int get hashCode => registrationUpload.hashCode ^ exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientRegistrationFinishResult &&
          runtimeType == other.runtimeType &&
          registrationUpload == other.registrationUpload &&
          exportKey == other.exportKey;
}

class ClientRegistrationStartResult {
  /// Opaque handle; pass this back to `client_registration_finish`.
  final PlatformInt64 stateId;

  /// Serialized RegistrationRequest — send this to the server.
  final Uint8List registrationRequest;

  const ClientRegistrationStartResult({
    required this.stateId,
    required this.registrationRequest,
  });

  @override
  int get hashCode => stateId.hashCode ^ registrationRequest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientRegistrationStartResult &&
          runtimeType == other.runtimeType &&
          stateId == other.stateId &&
          registrationRequest == other.registrationRequest;
}

class ServerLoginStartResult {
  /// Opaque handle; pass this back to `server_login_finish`.
  final PlatformInt64 stateId;

  /// Serialized CredentialResponse — send this to the client.
  final Uint8List credentialResponse;

  const ServerLoginStartResult({
    required this.stateId,
    required this.credentialResponse,
  });

  @override
  int get hashCode => stateId.hashCode ^ credentialResponse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerLoginStartResult &&
          runtimeType == other.runtimeType &&
          stateId == other.stateId &&
          credentialResponse == other.credentialResponse;
}
